networks:
  default:
    external: true
    name: main

services:
  moyoki:
    image: git.dev.aquaswim.my.id/personal/moyoki:latest
    container_name: moyoki
    restart: unless-stopped
    volumes:
      - moyoki_data:/config
    environment:
      - TZ=Asia/Jakarta
    labels:
      - collect_logs=true
      - traefik.enable=true
      # Router 1 -> Service 1 (Port 3001)
      - traefik.http.routers.mock.rule=Host(`mock.home.aquaswim.my.id`)
      - traefik.http.routers.mock.service=mock
      - traefik.http.services.mock.loadbalancer.server.port=3001

      # Router 2 -> Service 2 (Port 3000)
      - traefik.http.routers.mockui.rule=Host(`mock-ui.home.aquaswim.my.id`)
      - traefik.http.routers.mockui.service=mockui
      - traefik.http.services.mockui.loadbalancer.server.port=3000
    deploy:
      resources:
        limits:
          cpus: '0.15'
          memory: 64M

volumes:
  moyoki_data: