networks:
  default:
    external: true
    name: main

services:
  moyoki:
    image: git.dev.aquaswim.my.id/personal/moyoki:latest
    container_name: moyoki
    restart: unless-stopped
    volumes:
      - moyoki_data:/config
    environment:
      - TZ=Asia/Jakarta
    labels:
      - collect_logs=true
      - traefik.enable=true
      - traefik.http.routers.mock.rule=Host(`mock.home.aquaswim.my.id`)
      - traefik.http.services.mock.loadbalancer.server.port=3001
      - traefik.http.routers.mock-ui.rule=Host(`mock-ui.home.aquaswim.my.id`)
      - traefik.http.services.mock-ui.loadbalancer.server.port=3000
    deploy:
      resources:
        limits:
          cpus: '0.15'
          memory: 64M

volumes:
  moyoki_data: